pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - label=ready-to-merge
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
      label:
        remove: ["ready-to-merge"]
#   - name: delete head branch after merge
#     conditions: []
#     actions:
#       delete_head_branch: {}
